In [3]:
import numpy as np

## DataTypes & Attributes

In [4]:
# NumPy's main datatype is `ndarray`
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1.0, 2, 3], [4.5, 5, 6]])
a2

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]])

In [7]:
a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 0]],
               [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]]]
             )
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  0]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a4 = np.array([[1, 2], [3, 4]])
a4.shape

(2, 2)

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [14]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [16]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  4.5  5.0  6.0

## 2. Creating arrays

In [17]:
ones = np.ones([2, 3])
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
zeros = np.zeros((3, 2))
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [25]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[7, 3, 5, 5, 8],
       [9, 8, 8, 7, 2],
       [4, 3, 3, 9, 1]])

In [29]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.35584206, 0.62265161, 0.6498762 ],
       [0.41019861, 0.69996451, 0.92900766],
       [0.52729928, 0.94933488, 0.81491723],
       [0.40398696, 0.24062389, 0.43504519],
       [0.20941867, 0.71036648, 0.65663606]])

In [30]:
random_array_2.shape

(5, 3)

In [31]:
random_array_2.size

15

In [41]:
# pseudo-random numbers
# produces pseudo-random numbers that are reproducible
np.random.seed(seed=56)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 4, 0],
       [2, 9, 7],
       [6, 4, 9],
       [7, 1, 8],
       [2, 0, 5]])

In [38]:
random_array_4.shape

(5, 3)

In [44]:
np.random.seed(7)
random_array_5 = np.random.random([5, 3])
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [48]:
# still the same, although different JupyterLab cell
random_array_5

array([[0.20484909, 0.49076589, 0.37238469],
       [0.47740115, 0.36589039, 0.83791799],
       [0.76864751, 0.31399468, 0.57262533],
       [0.27604905, 0.45284293, 0.35297837],
       [0.65739946, 0.37035108, 0.45909298]])

In [49]:
# newly generated array doesn't use seed
random_array_5 = np.random.random([5, 3])
random_array_5

array([[0.71932412, 0.41299183, 0.90642327],
       [0.18045162, 0.74111887, 0.42237404],
       [0.42645357, 0.63437987, 0.5229062 ],
       [0.41488598, 0.00142688, 0.09226235],
       [0.70939439, 0.5243456 , 0.69616046]])

## 3. Viewing arrays and matrices

In [50]:
random_array_4

array([[5, 4, 0],
       [2, 9, 7],
       [6, 4, 9],
       [7, 1, 8],
       [2, 0, 5]])

In [51]:
np.unique(random_array_4)

array([0, 1, 2, 4, 5, 6, 7, 8, 9])

In [52]:
a1

array([1, 2, 3])

In [53]:
a2

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]])

In [54]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  0]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [55]:
a1[0]

1

In [57]:
a1[1]

2

In [58]:
a2[0]

array([1., 2., 3.])

In [60]:
a2[0][1]

2.0

In [61]:
a3.shape

(2, 3, 3)

In [62]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [63]:
a3[:1, :2, :1]

array([[[1],
        [4]]])

In [66]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[0, 7, 2, 0, 3],
         [9, 8, 3, 7, 1],
         [0, 1, 4, 6, 1],
         [0, 1, 0, 1, 8]],

        [[4, 1, 6, 8, 5],
         [2, 4, 7, 4, 1],
         [2, 8, 5, 2, 9],
         [6, 2, 5, 7, 7]],

        [[5, 5, 6, 0, 6],
         [4, 6, 2, 6, 8],
         [7, 0, 5, 8, 9],
         [7, 7, 6, 2, 5]]],


       [[[6, 1, 9, 3, 4],
         [0, 3, 5, 6, 4],
         [0, 4, 1, 5, 2],
         [4, 8, 7, 5, 7]],

        [[5, 3, 7, 6, 2],
         [3, 1, 1, 8, 4],
         [2, 1, 7, 0, 8],
         [8, 1, 2, 3, 0]],

        [[1, 1, 5, 5, 6],
         [0, 9, 3, 2, 4],
         [2, 8, 4, 9, 0],
         [0, 2, 6, 3, 9]]]])

In [67]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [68]:
a4[1][0][0]

array([6, 1, 9, 3, 4])

## 4. Manipulating & comparing arrays

In [69]:
a1

array([1, 2, 3])

In [70]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [71]:
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [72]:
a1 - ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [74]:
a1

array([1, 2, 3])

In [75]:
a2

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]])

In [76]:
a1 * a2

array([[ 1. ,  4. ,  9. ],
       [ 4.5, 10. , 18. ]])

In [77]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  0]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [78]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [79]:
a2.dot(a3)

array([[[ 30. ,  36. ,  15. ],
        [ 84. ,  90. ,  96. ]],

       [[ 66.5,  82. ,  43.5],
        [206. , 221.5, 237. ]]])

In [80]:
a1 / ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [82]:
# Floor division removes decimals (rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [83]:
a2 ** 2

array([[ 1.  ,  4.  ,  9.  ],
       [20.25, 25.  , 36.  ]])

In [84]:
np.square(a2)

array([[ 1.  ,  4.  ,  9.  ],
       [20.25, 25.  , 36.  ]])

In [85]:
a1 % 2

array([1, 0, 1])

In [87]:
np.mod(a1, 2)

array([1, 0, 1])

In [88]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [89]:
np.log(a2)

array([[0.        , 0.69314718, 1.09861229],
       [1.5040774 , 1.60943791, 1.79175947]])

### Aggregation
Aggregation = performing the same operation on a number of things

In [90]:
list1 = [1, 2, 3]
type(list1)

list

In [91]:
sum(list1)

6

In [92]:
type(a1)

numpy.ndarray

In [93]:
sum(a1)

6

In [94]:
np.sum(a1)

6

- Use Python's methods on Python datatype
- use NumPy's methods on NumPy arrays

In [99]:
# create a big array
massive_array = np.random.random(100000)
massive_array.size

100000

In [100]:
massive_array[:10]

array([0.19228075, 0.00140182, 0.85928738, 0.76869309, 0.93028759,
       0.11032309, 0.57856859, 0.62297163, 0.31625189, 0.41727516])

In [106]:
%timeit sum(massive_array) # Python's sum
%timeit np.sum(massive_array) # NumPy's np.sum

30.4 ms ± 408 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
36.9 µs ± 504 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [107]:
a2

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]])

In [108]:
np.mean(a2)

3.5833333333333335

In [109]:
np.max(a2)

6.0

In [113]:
# standard deviation = a measure of how spread out a group of numbers is from the mean
np.std(a2)

1.7420454133639063

In [114]:
# variance = measure of the average degree to which each number is different from the mean
# higher variance = wider range of numbers
np.var(a2)

3.0347222222222228

In [116]:
# standard deviation = square root of variance
np.sqrt(np.var(a2))

1.7420454133639063