# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documnetation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [11]:
# Create a 1-dimensional NumPy array using np.array()
arr1 = np.array([1])
arr1.ndim

# Create a 2-dimensional NumPy array using np.array()
arr2 = np.random.randint(10, size=(12,2))
arr2.ndim

# Create a 3-dimensional Numpy array using np.array()
arr3 = np.random.randint(10, size=(13,3,3))
arr3.ndim

3

In [13]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
arr1.shape, arr1.dtype, arr1.size, type(arr1)

((1,), dtype('int64'), 1, numpy.ndarray)

In [14]:
# Attributes of 2-dimensional array
arr2.shape, arr2.dtype, arr2.size, type(arr2)

((12, 2), dtype('int64'), 24, numpy.ndarray)

In [15]:
# Attributes of 3-dimensional array
arr3.shape, arr3.dtype, arr3.size, type(arr3)

((13, 3, 3), dtype('int64'), 117, numpy.ndarray)

In [24]:
arr2

array([[5, 1],
       [3, 3],
       [9, 9],
       [8, 1],
       [2, 9],
       [7, 4],
       [9, 0],
       [2, 7],
       [2, 7],
       [7, 2],
       [6, 7],
       [9, 3]])

In [27]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(arr2, index=["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l"], columns=["sample value 1", "sample value 2"])
df

sample value 1  sample value 2
a               5               1
b               3               3
c               9               9
d               8               1
e               2               9
f               7               4
g               9               0
h               2               7
i               2               7
j               7               2
k               6               7
l               9               3

In [8]:
# Create an array of shape (7, 2, 3) of only zeros


In [30]:
# Create an array of shape (10, 2) with only ones
arr4 = np.ones(shape=(10,2))
arr4.shape

(10, 2)

In [31]:
# Create an array within a range of 0 and 100 with step 3
range_arr = np.arange(0, 100, 3)
range_arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [32]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_arr = np.random.randint(10, size=(7,2))
random_arr

array([[5, 0],
       [1, 9],
       [1, 2],
       [5, 5],
       [5, 9],
       [6, 1],
       [4, 0]])

In [35]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
randf_arr = np.random.uniform(size=(3,5))
randf_arr.shape

(3, 5)

In [40]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
rand_arr = np.random.randint(10, size=(4,6))
rand_arr


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

- numbers are the same, because we set the random seed

In [43]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rand_arr2 = np.random.randint(10, size=(3,7))
# Find the unique numbers in the array you just created
np.unique(rand_arr2)

array([0, 1, 2, 3, 4, 6, 7, 8, 9])

In [47]:
rand_arr2

array([[3, 7, 6, 8, 7, 4, 1],
       [4, 7, 9, 8, 8, 0, 8],
       [6, 8, 7, 0, 7, 7, 2]])

In [45]:
# Find the 0'th index of the latest array you created
rand_arr2[0]

array([3, 7, 6, 8, 7, 4, 1])

In [46]:
# Get the first 2 values of the first 2 rows of the latest array
rand_arr2[:2, :2]

array([[3, 7],
       [4, 7]])

In [49]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
rand_arr3 = np.random.randint(10, size=(3,5))
ones = np.ones(shape=(3,5))

In [51]:
rand_arr3

array([[6, 6, 7, 4, 2],
       [7, 5, 2, 0, 2],
       [4, 2, 0, 4, 9]])

In [52]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [53]:
# Add the two arrays together
sum = ones + rand_arr3
sum

array([[ 7.,  7.,  8.,  5.,  3.],
       [ 8.,  6.,  3.,  1.,  3.],
       [ 5.,  3.,  1.,  5., 10.]])

In [54]:
# Create another array of ones of shape (5, 3)
another_ones = np.ones(shape=(5,3))
another_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [55]:
# Try add the array of ones and the other most recent array together
# doesnt' work!

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [58]:
rand_arr3_t = rand_arr3.T
another_sum = another_ones + rand_arr3_t
another_sum

array([[ 7.,  8.,  5.],
       [ 7.,  6.,  3.],
       [ 8.,  3.,  1.],
       [ 5.,  1.,  5.],
       [ 3.,  3., 10.]])

In [59]:
# Create another array of ones of shape (3, 5)
more_ones = np.ones(shape=(3,5))

In [60]:
# Subtract the new array of ones from the other most recent array
rand_arr3 - more_ones

array([[ 5.,  5.,  6.,  3.,  1.],
       [ 6.,  4.,  1., -1.,  1.],
       [ 3.,  1., -1.,  3.,  8.]])

In [61]:
# Multiply the ones array with the latest array
rand_arr3 * more_ones

array([[6., 6., 7., 4., 2.],
       [7., 5., 2., 0., 2.],
       [4., 2., 0., 4., 9.]])

In [62]:
# Take the latest array to the power of 2 using '**'
rand_arr3 ** more_ones

array([[6., 6., 7., 4., 2.],
       [7., 5., 2., 0., 2.],
       [4., 2., 0., 4., 9.]])

In [63]:
# Do the same thing with np.square()
np.square(rand_arr3)

array([[36, 36, 49, 16,  4],
       [49, 25,  4,  0,  4],
       [16,  4,  0, 16, 81]])

In [65]:
# Find the mean of the latest array using np.mean()
np.mean(rand_arr3)

4.0

In [66]:
# Find the maximum of the latest array using np.max()
np.max(rand_arr3)

9

In [67]:
# Find the minimum of the latest array using np.min()
np.min(rand_arr3)

0

In [68]:
# Find the standard deviation of the latest array
np.std(rand_arr3)

2.581988897471611

In [69]:
# Find the variance of the latest array
np.var(rand_arr3)

6.666666666666667

In [72]:
# Reshape the latest array to (3, 5, 1)
rand_arr3.reshape(3,5,1)

array([[[6],
        [6],
        [7],
        [4],
        [2]],

       [[7],
        [5],
        [2],
        [0],
        [2]],

       [[4],
        [2],
        [0],
        [4],
        [9]]])

In [73]:
# Transpose the latest array
rand_arr3.T

array([[6, 7, 4],
       [6, 5, 2],
       [7, 2, 0],
       [4, 0, 4],
       [2, 2, 9]])

What does the transpose do?
* it "flips" the axis' of the ndarray

In [75]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
yaa1 = np.random.randint(10, size=(3,3))
yaa2 = np.random.randint(10, size=(3,2))

In [76]:
yaa1

array([[2, 5, 1],
       [9, 8, 4],
       [5, 3, 9]])

In [77]:
yaa2

array([[6, 8],
       [6, 0],
       [0, 8]])

In [78]:
# Perform a dot product on the two newest arrays you created
np.dot(yaa1, yaa2)

array([[ 42,  24],
       [102, 104],
       [ 48, 112]])

In [80]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
yaa3 = np.random.randint(10, size=(4,3))
yaa4 = np.random.randint(10, size=(4,3))

In [81]:
# Perform a dot product on the two newest arrays you created
# doesn't work

It doesn't work. How would you fix it?

In [82]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(yaa3.T, yaa4)

array([[ 72, 109,  77],
       [ 81, 107,  49],
       [150, 100,  86]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [83]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
yaa5 = np.random.randint(10, size=(5,6,3))
yaa6 = np.random.randint(10, size=(5,6,3))

In [84]:
# Compare the two arrays with '>'
yaa5 > yaa6

array([[[False, False, False],
        [False, False, False],
        [False,  True,  True],
        [ True, False, False],
        [False, False,  True],
        [ True,  True, False]],

       [[False, False,  True],
        [ True, False, False],
        [False,  True, False],
        [ True,  True,  True],
        [False,  True,  True],
        [ True,  True, False]],

       [[False,  True, False],
        [False, False,  True],
        [False,  True, False],
        [ True,  True, False],
        [ True, False,  True],
        [False, False,  True]],

       [[False, False, False],
        [ True,  True, False],
        [False, False, False],
        [ True, False,  True],
        [ True,  True, False],
        [False, False, False]],

       [[ True, False,  True],
        [False, False, False],
        [False,  True, False],
        [ True,  True,  True],
        [False,  True, False],
        [ True, False, False]]])

What happens when you compare the arrays with `>`?
* it shows the result of the operator comparison element-wise

In [85]:
# Compare the two arrays with '>='
yaa5 >= yaa6

array([[[False, False, False],
        [False, False,  True],
        [False,  True,  True],
        [ True, False, False],
        [False,  True,  True],
        [ True,  True,  True]],

       [[ True, False,  True],
        [ True, False,  True],
        [ True,  True, False],
        [ True,  True,  True],
        [False,  True,  True],
        [ True,  True, False]],

       [[False,  True, False],
        [False, False,  True],
        [False,  True,  True],
        [ True,  True, False],
        [ True, False,  True],
        [ True, False,  True]],

       [[ True,  True, False],
        [ True,  True, False],
        [False,  True, False],
        [ True, False,  True],
        [ True,  True, False],
        [False, False, False]],

       [[ True, False,  True],
        [False, False, False],
        [False,  True, False],
        [ True,  True,  True],
        [False,  True, False],
        [ True,  True, False]]])

In [86]:
# Find which elements of the first array are greater than 7
yaa5 > 7

array([[[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False,  True, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False,  True, False],
        [False, False, False]],

       [[False,  True, False],
        [False, False, False],
        [False,  True, False],
        [False, False, False],
        [False, False,  True],
        [ True, False, False]],

       [[ True, False, False],
        [ True,  True, False],
        [False, False, False],
        [False, False, False],
        [ True,  True, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False,  True, False],
        [ True, False, False]]])

In [87]:
# Which parts of each array are equal? (try using '==')
yaa5 == yaa6

array([[[False, False, False],
        [False, False,  True],
        [False, False, False],
        [False, False, False],
        [False,  True, False],
        [False, False,  True]],

       [[ True, False, False],
        [False, False,  True],
        [ True, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False,  True],
        [False, False, False],
        [False, False, False],
        [ True, False, False]],

       [[ True,  True, False],
        [False, False, False],
        [False,  True, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False,  True, False]]])

In [88]:
# Sort one of the arrays you just created in ascending order
yaa5

array([[[0, 4, 0],
        [7, 0, 0],
        [1, 1, 5],
        [6, 4, 0],
        [0, 2, 1],
        [4, 9, 5]],

       [[6, 3, 6],
        [7, 0, 5],
        [7, 4, 3],
        [1, 5, 5],
        [0, 8, 5],
        [2, 3, 3]],

       [[2, 9, 2],
        [2, 3, 6],
        [3, 8, 0],
        [7, 6, 1],
        [7, 0, 8],
        [8, 1, 6]],

       [[9, 2, 6],
        [9, 8, 3],
        [0, 1, 0],
        [4, 4, 6],
        [8, 8, 2],
        [2, 2, 3]],

       [[7, 5, 7],
        [0, 7, 3],
        [0, 7, 3],
        [5, 7, 3],
        [2, 8, 2],
        [8, 1, 1]]])

In [89]:
np.sort(yaa5)

array([[[0, 0, 4],
        [0, 0, 7],
        [1, 1, 5],
        [0, 4, 6],
        [0, 1, 2],
        [4, 5, 9]],

       [[3, 6, 6],
        [0, 5, 7],
        [3, 4, 7],
        [1, 5, 5],
        [0, 5, 8],
        [2, 3, 3]],

       [[2, 2, 9],
        [2, 3, 6],
        [0, 3, 8],
        [1, 6, 7],
        [0, 7, 8],
        [1, 6, 8]],

       [[2, 6, 9],
        [3, 8, 9],
        [0, 0, 1],
        [4, 4, 6],
        [2, 8, 8],
        [2, 2, 3]],

       [[5, 7, 7],
        [0, 3, 7],
        [0, 3, 7],
        [3, 5, 7],
        [2, 2, 8],
        [1, 1, 8]]])

In [90]:
# Sort the indexes of one of the arrays you just created
np.argsort(yaa5)

array([[[0, 2, 1],
        [1, 2, 0],
        [0, 1, 2],
        [2, 1, 0],
        [0, 2, 1],
        [0, 2, 1]],

       [[1, 0, 2],
        [1, 2, 0],
        [2, 1, 0],
        [0, 1, 2],
        [0, 2, 1],
        [0, 1, 2]],

       [[0, 2, 1],
        [0, 1, 2],
        [2, 0, 1],
        [2, 1, 0],
        [1, 0, 2],
        [1, 2, 0]],

       [[1, 2, 0],
        [2, 1, 0],
        [0, 2, 1],
        [0, 1, 2],
        [2, 0, 1],
        [0, 1, 2]],

       [[1, 0, 2],
        [0, 2, 1],
        [0, 2, 1],
        [2, 0, 1],
        [0, 2, 1],
        [1, 2, 0]]])

In [91]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(yaa6)

52

In [92]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(yaa6)

5

In [100]:
# Find the indexes with the maximum values down the verticial axis
# of one of the arrays you created
yaa6.argmax(0)

array([[3, 4, 2],
       [0, 4, 4],
       [4, 4, 3],
       [0, 3, 0],
       [3, 1, 3],
       [2, 2, 3]])

In [101]:
# Find the indexes with the minimum values across the horizontal axis
# of one of the arrays you created
yaa6.argmin(1)

array([[5, 2, 1],
       [3, 3, 4],
       [4, 0, 1],
       [3, 4, 3],
       [1, 5, 3]])

In [104]:
# Create an array of normally distributed random numbers
np.random.normal(250, 1, 111)

array([250.14983372, 250.14090737, 250.35441959, 248.11968741,
       250.966392  , 249.48905553, 251.21039863, 249.84876403,
       249.62547844, 248.70878389, 249.23449063, 250.42231376,
       248.6920857 , 248.00940045, 249.14245111, 250.84000538,
       251.78129108, 249.32258433, 248.45117132, 249.65687094,
       250.18385551, 250.57789714, 252.13464125, 250.22684882,
       251.65546163, 249.53707458, 250.08656581, 249.40711727,
       249.31999567, 249.73659416, 249.71934512, 249.39602408,
       249.45074709, 251.09679625, 252.11311216, 249.50159338,
       249.67560455, 250.524609  , 253.18703334, 250.08416352,
       250.97263287, 251.54447484, 250.34406813, 250.92623254,
       250.60783854, 251.03251279, 248.96559764, 250.20428294,
       250.48121773, 250.46705717, 251.13701742, 250.44689014,
       248.85505148, 250.59131612, 249.11692134, 249.30062195,
       249.58149112, 249.88858122, 248.4562746 , 251.11689344,
       248.84448409, 251.57011062, 248.87504826, 251.28

In [107]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.